import 'reactflow/dist/style.css';


export const metadata = {
  title: 'Blakprint',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode | JSX.Element }) {
  return (
    <html lang="en">
      <body className="h-screen m-0 w-full overflow-hidden">{children}</body>
    </html>
  )
}
